[dossier]
dossier_extraction = "data/extraction"
dossier_extraction_tmp = "data/extraction/tmp"

meteo_name_extraction = "meteo"
nappe_name_extraction = "nappes"
etp_name_extraction = "etp"
impermeabilite_name_extraction = "impermeabilite"

mailles_name_extraction = "maille"
communes_name_extraction = "communes"

dossier_fusion = "data/fusion"

dossier_nappe_inertielle = "data/clusterisation/inertielle"
dossier_nappe_reactive = "data/clusterisation/reactive"

dossier_completion = "data/completion"
dossier_completion_inertielle = "data/completion/inertielle"
dossier_completion_reactive = "data/completion/reactive"

dossier_summary = "data"
summary_name = "summary.csv"

dossier_model = "models"
dossier_scaler = "scaler"

[entrainement_model]
window_size = 120
models = ["CNN","LSTM","BILSTM"] # valeur : ["CNN","LSTM","BILSTM"]
global = true
fine_tune = true
local = false

[completion]
[completion.niveau_nappe_eau]
realiser = true
methodes = ["polynome"]

[completion.PRELIQ_Q]
realiser = true
methodes = ["lineaire","cubique", "global/CNN"]

[completion.T_Q]
methodes = []
realiser = true

[completion.ETP_Q]
realiser = false
methodes = []


[pipeline]
departements = [45] # liste des departements avec lesquels on veut travailler
qualite = 30 # nombre d'année de donné que possède châque dataset. valeur : 30, 20, 10, 5, 0

type = [] # type de nappe sur lequel on veut travailler. valeur : "reactive", "inertielle"  ou []

extraction = false
fusion = false
clusterisation = false
entrainement = false
completion = true